In [3]:
import numpy

Создать вектор (одномерный массив) размера 10, заполненный
нулями.

In [4]:
numpy.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор (одномерный массив) размера 10, заполненный
нулями, пятый элемент должен быть равен

In [5]:
v = numpy.zeros(10)
v[5] = 1
print(v)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


. Создать вектор (одномерный массив) размера 20. Заполнить его
случайными значениями. Найти индексы ненулевых элементов

In [6]:
v = numpy.random.random(20)
h = numpy.nonzero(v)
print(v)
print(h)

[0.78229121 0.19448415 0.31194604 0.39158112 0.70787345 0.74725591
 0.39928671 0.30124554 0.32170649 0.29183065 0.50615907 0.99908565
 0.44125249 0.49157189 0.79082391 0.93548581 0.18345228 0.09827796
 0.301493   0.66845683]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),)


Создать массив 3x3x3. Заполнить его случайными значениями

In [7]:
v = numpy.random.random((3,3,3))
print(v)

[[[0.4348995  0.63971945 0.27545029]
  [0.12717151 0.67831825 0.1480101 ]
  [0.92893744 0.5328711  0.78033258]]

 [[0.1250723  0.69219514 0.22212205]
  [0.45917261 0.96916737 0.62058928]
  [0.71808551 0.33158945 0.13853779]]

 [[0.57217043 0.39144288 0.59698666]
  [0.54153608 0.18714923 0.03651459]
  [0.98393303 0.40128208 0.91142608]]]


Создать вектор (одномерный массив) размера 10. Заполнить его
случайными значениями. Найти среднее значение всех элементов

In [8]:
v = numpy.random.random(10)
h = numpy.mean(v)
print(h)

0.37438797094653187


 Создать две матрицы 5x3 и 3x2. Найти их произведение.

In [9]:
v = numpy.random.random((5,3))
m = numpy.random.random((3,2))
j = numpy.dot(v, m)
print(j)

[[1.29963768 0.30807646]
 [0.23816845 0.16732291]
 [0.79108544 0.16551816]
 [0.61703436 0.14969651]
 [1.23072852 0.43617891]]


Создать две матрицы 4x4 и 4x4. Найти их произведение. Найти
диагональные элементы произведения матриц

In [10]:
v = numpy.random.random((4,4))
m = numpy.random.random((4,4))
j = numpy.dot(v, m)
g = numpy.diag(j)
print(g)

[0.62559169 0.13829739 0.90045771 1.3324192 ]


Создать вектор (одномерный массив) размера 20. Заполнить его
случайными значениями. Заменить максимальный элемент на ноль

In [11]:
v = numpy.random.random(20)
m = numpy.argmax(v)
v[m] = 0
print(v)


[0.52051098 0.71123223 0.11163107 0.82627481 0.62671177 0.23905597
 0.73426564 0.36537548 0.8843213  0.09751169 0.49204876 0.88882744
 0.8967762  0.43004744 0.         0.42260882 0.82678477 0.35906316
 0.34135318 0.79174161]


Создать вектор (одномерный массив) размера 20. Заполнить его
случайными значениями. Напечатать все значения в массиве без повторений.

In [12]:
v = numpy.random.randint(1,100,20)
my_set = numpy.unique(v)
print(my_set)

[ 2 14 20 22 32 37 44 45 50 51 59 65 75 84 86 88 91 93 97]


Создать матрицу. Отнять среднее из каждой строки в матрице

In [13]:
v = numpy.random.randint(1,100,size=(4,4))
print('v: \n', v)
for i in v:
  m = i.mean()
  for j in range(0, i.size):
    i[j] -= m
print('v: \n', v)

v: 
 [[17 44 40 33]
 [89 59 22 36]
 [40 43 19 54]
 [ 1 90 77 46]]
v: 
 [[-16  10   6   0]
 [ 37   7 -29 -15]
 [  1   4 -20  15]
 [-52  36  23  -7]]


Создать матрицу. Поменять две строки в матрице

In [14]:
v = numpy.random.randint(1, 100, size=(4,4))
print('v: \n', v)
v[[0, 2]] = v[[2, 0]]
print('v: \n', v)

v: 
 [[90 66 79 95]
 [93 59 90 19]
 [78 15 46 88]
 [17 88 43 24]]
v: 
 [[78 15 46 88]
 [93 59 90 19]
 [90 66 79 95]
 [17 88 43 24]]


Создать вектор (одномерный массив) размера 20. Заполнить его
случайными значениями. Найти n наибольших значений в векторе

In [15]:
v = numpy.random.randint(1, 100, 20)
n=numpy.random.randint(1, 20)
print(n)
print('v: \n', v)
v.sort()
print('v: \n', v)
print('v: \n', v[numpy.size(v)-n:numpy.size(v)])


12
v: 
 [77 70 71 85 63 39 95 43 22 75 89 14 35 73 79 23 82 53 49 22]
v: 
 [14 22 22 23 35 39 43 49 53 63 70 71 73 75 77 79 82 85 89 95]
v: 
 [53 63 70 71 73 75 77 79 82 85 89 95]


Создать матрицу размера 5x5 и заполнить ее случайными целыми
числами от 1 до 10. Найти сумму элементов каждой строки

In [16]:
v = numpy.random.randint(1, 10, size=(5,5))
print('v: \n', v)
for i in v:
  s = i.sum()
  print('v[',i,'] :' , s, '\n')

v: 
 [[6 5 5 7 2]
 [7 5 8 1 8]
 [9 6 5 8 5]
 [4 4 1 4 3]
 [1 5 2 4 2]]
v[ [6 5 5 7 2] ] : 25 

v[ [7 5 8 1 8] ] : 29 

v[ [9 6 5 8 5] ] : 33 

v[ [4 4 1 4 3] ] : 16 

v[ [1 5 2 4 2] ] : 14 



Создать вектор (одномерный массив) размера 10. Заполнить его
случайными значениями от -1 до 1. Заменить отрицательные значения на -1,
положительные на 1, и оставить нулевые значения без изменений


In [17]:
v = numpy.random.uniform(-1,1,size=10)
print('v: \n', v)
for i in range(0,numpy.size(v)):
    if(v[i]<0):
      v[i]=-1
    if(v[i]>0):
      v[i]=1
print('v: \n', v)


v: 
 [-0.62689326 -0.40030806  0.32290977 -0.38581406 -0.92404225  0.13438724
  0.80674641 -0.8738966   0.58582435 -0.6258373 ]
v: 
 [-1. -1.  1. -1. -1.  1.  1. -1.  1. -1.]


Создать вектор (одномерный массив) размера 12 и заполнить его
случайными значениями от 1 до 100. Разделить вектор на 3 равные части и
найти сумму элементов в каждой части

In [18]:
v = numpy.random.uniform(1,100,size=12)
len = numpy.array_split(v,3)
print('v: \n', v)
print('array: \n',len)
for i in range(0,3):
  sum=len[i].sum()
  print(i,':',sum,'\n')

v: 
 [31.86674371 37.58708807 98.04658857 36.54394785 28.77762518 27.43904233
  3.91924747  8.42005666 79.09675523 56.6147833  13.29021062  7.90541524]
array: 
 [array([31.86674371, 37.58708807, 98.04658857, 36.54394785]), array([28.77762518, 27.43904233,  3.91924747,  8.42005666]), array([79.09675523, 56.6147833 , 13.29021062,  7.90541524])]
0 : 204.04436820139676 

1 : 68.55597164033209 

2 : 156.90716438512118 

